name: future2025

networks:
  future2025_network:
    driver: bridge

services:
  frontend:
    container_name: future2025_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    restart: always
    networks:
      - future2025_network

  backend:
    container_name: future2025_backend
    build:
      context: .
      dockerfile: infra/docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: >
      sh -c "sleep 10 &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - ENV=development
      - CHOKIDAR_USEPOLLING=true
      - POSTGRES_DB=futurecyber_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dU2q4Lpm12@#$
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
    restart: always
    networks:
      - future2025_network

  db:
    image: postgres:latest
    container_name: future2025_db
    restart: always
    environment:
      POSTGRES_DB: futurecyber_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dU2q4Lpm12@#$

    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - future2025_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d futurecyber_db" ]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  db_data:
    driver: local
