# Generated by Django 5.1.6 on 2025-02-14 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('GV', 'Govern'), ('ID', 'Identity'), ('PR', 'Protect'), ('DE', 'Detect'), ('RS', 'Response'), ('RC', 'Recovery')], max_length=2)),
                ('question', models.TextField()),
                ('policy_maturity', models.IntegerField(choices=[(1, 'Inicial'), (2, 'Gerenciado'), (3, 'Definido'), (4, 'Repetido'), (5, 'Otimizado')])),
                ('practice_maturity', models.IntegerField(choices=[(1, 'Inicial'), (2, 'Gerenciado'), (3, 'Definido'), (4, 'Repetido'), (5, 'Otimizado')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
