# Generated by Django 5.1.7 on 2025-03-26 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlassessment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlassessment',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='assessments.question'),
        ),
    ]
