# Generated by Django 5.1.7 on 2025-03-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('GV', 'Govern'), ('ID', 'Identity'), ('PR', 'Protect'), ('DE', 'Detect'), ('RS', 'Response'), ('RC', 'Recovery')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='question',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=500),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
