# Generated by Django 5.1.6 on 2025-02-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('score', models.IntegerField()),
                ('category', models.CharField(choices=[('high', 'Alta'), ('medium', 'Média'), ('low', 'Baixa')], max_length=100)),
                ('assessment_date', models.DateField()),
            ],
        ),
    ]
