# Generated by Django 5.1.7 on 2025-03-26 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_alter_question_category_alter_question_weight_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('politica', models.IntegerField(choices=[(1, 'Inicial'), (2, 'Repetido'), (3, 'Definido'), (4, 'Gerenciado'), (5, 'Otimizado')])),
                ('pratica', models.IntegerField(choices=[(1, 'Inicial'), (2, 'Repetido'), (3, 'Definido'), (4, 'Gerenciado'), (5, 'Otimizado')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'question')},
            },
        ),
    ]
