# Generated by Django 5.1.7 on 2025-03-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_riskassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlassessment',
            name='category',
            field=models.CharField(blank=True, choices=[('security', 'Segurança'), ('privacy', 'Privacidade'), ('compliance', 'Compliance')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='controlassessment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controlassessment',
            name='status',
            field=models.CharField(blank=True, choices=[('in_progress', 'Em progresso'), ('completed', 'Concluído'), ('pending', 'Pendente')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='controlassessment',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='controlassessment',
            name='policy_maturity',
            field=models.IntegerField(blank=True, choices=[(1, 'Inicial'), (2, 'Gerenciado'), (3, 'Definido'), (4, 'Repetido'), (5, 'Otimizado')], null=True),
        ),
        migrations.AlterField(
            model_name='controlassessment',
            name='practice_maturity',
            field=models.IntegerField(blank=True, choices=[(1, 'Inicial'), (2, 'Gerenciado'), (3, 'Definido'), (4, 'Repetido'), (5, 'Otimizado')], null=True),
        ),
    ]
